services:
  airflow:
    build: .
    image: sales-airflow:latest
    command: standalone
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      PYTHONPATH: /opt/airflow/project
      SNOWFLAKE_ACCOUNT: ${SNOWFLAKE_ACCOUNT}
      SNOWFLAKE_USER: ${SNOWFLAKE_USER}
      SNOWFLAKE_PRIVATE_KEY_FILE: /opt/airflow/keys/rsa_key.p8
      WAPE_THRESHOLD: "0.12"
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    volumes:
      - ./dags:/opt/airflow/dags
      - ./:/opt/airflow/project
      - ${HOME}/.snowflake/rsa_key.p8:/opt/airflow/keys/rsa_key.p8:ro
